### PR TITLE
set ulimit value to 4096 (issue #9)

### PR DESCRIPTION
**Pull request by tyiss**
set the value of ulimit to 4096.

to do that it upload a new */etc/security/limits.conf* which adds the following line:
<pre>
* soft nofile 4096
</pre>

### CODE REVIEW

**Comment by ahmadnassri** [comment]
@tyiss is this really needed? why can't you call the `ulimit` option through the shell in `provision.sh`, rather than updating the config file? that way, its set on every bootup?

**Comment by tyiss** [comment]
@ahmadnassri 

I was trying to do it the way you suggested. by adding to provision.sh:
<pre>ulimit -n 4096</pre>

then after ssh to the machine the value is still 1024. not sure why.

I know my change diff is seems big, but its really, as i wrote, one additional line to  /etc/security/limits.conf .

**Comment by ahmadnassri** [comment]
@tyiss the issue with changing the file, is you'd have to logout / in and potentially restart before seeing the result, i'll investigate the issue with using it directly on shell ...

**Comment by thibaultCha** [comment]
Any updates on this?

**Comment by ahmadnassri** [comment]
no update on my end, have not had a chance to test with dynamic ulimit setting

**Comment by thefosk** [comment]
Closed via #26

**Pull request closed without merging**
