### PR TITLE
Update box OS

### PR DESCRIPTION
**Pull request by p0pr0ck5**
Let's not use an unsupported OS anymore, yeah?

### CODE REVIEW

**Comment by Tieske** [comment]
the provisioning script fails for me. Does the box work for you?

```
==> default: Setting up postgresql-contrib-9.5 (9.5.7-1.pgdg12.4+1) ...
==> default: Processing triggers for libc-bin (2.19-0ubuntu6.11) ...
==> default:  * Restarting PostgreSQL 9.5 database server
==> default:    ...done.
==> default: Expanded display is on.
==> default: CREATE ROLE
==> default: CREATE DATABASE
==> default: CREATE DATABASE
==> default: Ign http://archive.ubuntu.com trusty InRelease
==> default: Hit http://security.ubuntu.com trusty-security InRelease
==> default: Hit http://archive.ubuntu.com trusty-updates InRelease
==> default: Hit http://security.ubuntu.com trusty-security/main Sources
==> default: Hit http://archive.ubuntu.com trusty-backports InRelease
==> default: Hit http://security.ubuntu.com trusty-security/universe Sources
==> default: Hit http://archive.ubuntu.com trusty Release.gpg
==> default: Hit http://security.ubuntu.com trusty-security/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/main Sources
==> default: Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/restricted Sources
==> default: Hit http://archive.ubuntu.com trusty-updates/universe Sources
==> default: Hit http://security.ubuntu.com trusty-security/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/multiverse Sources
==> default: Hit http://security.ubuntu.com trusty-security/universe Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
==> default: Hit https://apt.postgresql.org precise-pgdg InRelease
==> default: Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
==> default: Hit https://apt.postgresql.org precise-pgdg/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/main Sources
==> default: Hit http://archive.ubuntu.com trusty-backports/restricted Sources
==> default: Hit http://archive.ubuntu.com trusty-backports/universe Sources
==> default: Hit http://archive.ubuntu.com trusty-backports/multiverse Sources
==> default: Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
==> default: Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
==> default: Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
==> default: Ign https://apt.postgresql.org precise-pgdg/main Translation-en_US
==> default: Hit http://archive.ubuntu.com trusty Release
==> default: Ign https://apt.postgresql.org precise-pgdg/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/main Sources
==> default: Hit http://archive.ubuntu.com trusty/restricted Sources
==> default: Hit http://archive.ubuntu.com trusty/universe Sources
==> default: Hit http://archive.ubuntu.com trusty/multiverse Sources
==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/multiverse Translation-en
==> default: Hit http://archive.ubuntu.com trusty/restricted Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/restricted Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   libjemalloc1 redis-tools
==> default: The following NEW packages will be installed:
==> default:   libjemalloc1 redis-server redis-tools
==> default: 0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 410 kB of archives.
==> default: After this operation, 1,272 kB of additional disk space will be used.
==> default: Do you want to continue?
==> default:  [Y/n]
==> default: Abort.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Thijss-MBP:kong-vagrant thijs$
```

**Comment by p0pr0ck5** [comment]
Whups, I had that associated change on a separate branch and couldn't remember if it was updated. Yeah we need to add `-y` to the redis install. Re-up'd with this change.

**Comment by Tieske** [comment]
box builds now, but doesn't run:
```
Thijss-MBP:kong-vagrant thijs$ vagrant ssh
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-119-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Thu May 18 19:10:28 UTC 2017

  System load:  0.28              Processes:           81
  Usage of /:   3.6% of 39.34GB   Users logged in:     0
  Memory usage: 12%               IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.

New release '16.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


vagrant@vagrant-ubuntu-trusty-64:~$ kong start
migrating core for database kong
core migrated up to: 2015-01-12-175310_skeleton
core migrated up to: 2015-01-12-175310_init_schema
core migrated up to: 2015-11-23-817313_nodes
core migrated up to: 2016-02-29-142793_ttls
core migrated up to: 2016-09-05-212515_retries
core migrated up to: 2016-09-16-141423_upstreams
core migrated up to: 2016-12-14-172100_move_ssl_certs_to_core
core migrated up to: 2016-11-11-151900_new_apis_router_1
core migrated up to: 2016-11-11-151900_new_apis_router_2
core migrated up to: 2016-11-11-151900_new_apis_router_3
core migrated up to: 2016-01-25-103600_unique_custom_id
core migrated up to: 2017-01-24-132600_upstream_timeouts
core migrated up to: 2017-01-24-132600_upstream_timeouts_2
migrating hmac-auth for database kong
hmac-auth migrated up to: 2015-09-16-132400_init_hmacauth
migrating rate-limiting for database kong
rate-limiting migrated up to: 2015-08-03-132400_init_ratelimiting
rate-limiting migrated up to: 2016-07-25-471385_ratelimiting_policies
migrating cors for database kong
cors migrated up to: 2017-03-14_multiple_orgins
migrating ip-restriction for database kong
ip-restriction migrated up to: 2016-05-24-remove-cache
migrating key-auth for database kong
key-auth migrated up to: 2015-07-31-172400_init_keyauth
migrating jwt for database kong
jwt migrated up to: 2015-06-09-jwt-auth
jwt migrated up to: 2016-03-07-jwt-alg
migrating galileo for database kong
galileo migrated up to: 2016-04-15_galileo-import-mashape-analytics
migrating oauth2 for database kong
oauth2 migrated up to: 2015-08-03-132400_init_oauth2
oauth2 migrated up to: 2016-07-15-oauth2_code_credential_id
oauth2 migrated up to: 2016-12-22-283949_serialize_redirect_uri
oauth2 migrated up to: 2016-09-19-oauth2_api_id
oauth2 migrated up to: 2016-12-15-set_global_credentials
migrating basic-auth for database kong
basic-auth migrated up to: 2015-08-03-132400_init_basicauth
basic-auth migrated up to: 2017-01-25-180400_unique_username
migrating response-ratelimiting for database kong
response-ratelimiting migrated up to: 2015-08-03-132400_init_response_ratelimiting
response-ratelimiting migrated up to: 2016-08-04-321512_response-rate-limiting_policies
migrating acl for database kong
acl migrated up to: 2015-08-25-841841_init_acl
32 migrations ran
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:23: nginx: [alert] mmap(MAP_ANON|MAP_SHARED, 134217728) failed (12: Cannot allocate memory)


  Run with --v (verbose) or --vv (debug) for more details
vagrant@vagrant-ubuntu-trusty-64:~$
```

**Comment by p0pr0ck5** [comment]
I cannot reproduce this. Try increasing the amount of memory you give to the VM?

**Comment by Tieske** [comment]
2048 works, but... only recently increased from 512 to 1024 (because Cassandra was added), and now even further...

**Comment by p0pr0ck5** [comment]
Welp, cassandra's expensive :P we could not run cassandra by default? Or we can bump the memory. Or try reducing the default kong shm size. I'm a fan of either of the first two ideas. Memory's cheap. Let's use it :)

**Comment by p0pr0ck5** [comment]
@Tieske ping :)

**Comment by Tieske** [comment]
I think cassandra needs to remain because it is required for the kong test suite to run. Hence probably best to increase memory default, which I just did.

**Pull request merged**
